[tool.poetry]
name = "ast-monitor-web"
version = "0.1.0"
description = ""
authors = ["Vanja Pajovic <vanja.pajovic@student.um.si>", "Bogdan <bogdan.kascelan@student.um.si>"]
readme = "README.md"
packages = [{include = "ast_monitor_web"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
