[tool.poetry]
name = "ast-monitor-web"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"
packages = [{include = "ast_monitor_web"}]

[tool.poetry.dependencies]
python = "^3.12"
Flask = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
